#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Erisred's notes

# Name of the author
author: Erisred

# Short bio or description (displayed in the header)
description: We'll see what happens

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /assets/images/images/malitovinv.png

url: https://erisred.github.io
baseurl: /

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: 
  facebook:
  flickr:
  github: erisred/
  instagram:
  linkedin: 
  pinterest:
  rss: rss
  twitter: 
  stackoverflow: 
  youtube: # channel/<your_long_string> or user/<user-name>
  playconsole:
